Algoritmo "positivo_negativo"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Verificar se um valor é positivo ou negativo
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 20/09/2026

Var
// Seção de Declarações das variáveis
numero: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um valor: ")
Leia(numero)

se numero >= 0 entao
   Escreval("O valor é positivo.")
senao
   Escreval("O valor é negativo.")
fimse

Fimalgoritmo