Algoritmo "maior_que_dez"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Verificar se um valor é maior que 10
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 20/09/2026

Var
// Seção de Declarações das variáveis
numero: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um valor: ")
Leia(numero)

se numero > 10 entao
   Escreval("É MAIOR QUE 10!")
senao
   Escreval("NÃO É MAIOR QUE 10!")
fimse

Fimalgoritmo