Algoritmo "area_retangulo"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcular a área de um retângulo
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 20/09/2026

Var
// Seção de Declarações das variáveis
base: real;
altura: real;
area: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite a base do retângulo: ")
Leia(base)

Escreval("Digite a altura do retângulo: ")
Leia(altura)

area <- base * altura

Escreval("A área do retângulo é: ", area)

Fimalgoritmo