Algoritmo "antecessor"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e apresentar o seu antecessor
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 19/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;
antecessor: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um número: ")
Leia(numero)

antecessor <- numero - 1

Escreval("O antecessor de ", numero, " é: ", antecessor)

Fimalgoritmo