Algoritmo "semnome"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converter graus Celsius em graus Fahrenheit
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 28/08/2026
Var

// Seção de Declarações das variáveis
grauC:real;
grauF:real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite os graus Celsius: ")
leia(grauC)

grauF <- (9 * grauC + 160) / 5

Escreval("Valor em graus Farenheit" + grauF)


Fimalgoritmo