Algoritmo "semnome"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Converter graus Fahrenheit em graus Celsius
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 28/08/2026
Var

// Seção de Declarações das variáveis
grauC:real;
grauF:real;


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite os graus Fahrenheit: ")
leia(grauF)

grauC <- (grauF -32) * (5/9)

Escreval("Valor em graus Celsius: ", grauC)


Fimalgoritmo