Algoritmo "operacoes_quatro_numeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Realizar operações de adição e multiplicação entre quatro números
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 27/09/2026

Var
// Seção de Declarações das variáveis
valorA: inteiro;
valorB: inteiro;
valorC: inteiro;
valorD: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite o valor de A: ")
Leia(valorA)

Escreval("Digite o valor de B: ")
Leia(valorB)

Escreval("Digite o valor de C: ")
Leia(valorC)

Escreval("Digite o valor de D: ")
Leia(valorD)

Escreval("A + B = ", valorA + valorB)
Escreval("A * B = ", valorA * valorB)

Escreval("A + C = ", valorA + valorC)
Escreval("A * C = ", valorA * valorC)

Escreval("A + D = ", valorA + valorD)
Escreval("A * D = ", valorA * valorD)

Escreval("B + C = ", valorB + valorC)
Escreval("B * C = ", valorB * valorC)

Escreval("B + D = ", valorB + valorD)
Escreval("B * D = ", valorB * valorD)

Escreval("C + D = ", valorC + valorD)
Escreval("C * D = ", valorC * valorD)

Fimalgoritmo