Algoritmo "quadrados_15_200"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;
quadrado: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para numero de 15 ate 200 faca
   quadrado <- numero * numero
   Escreval("O quadrado de ", numero, " é: ", quadrado)
fimpara

Fimalgoritmo