Algoritmo "tabuada"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar a tabuada de multiplicar de 1 até 10
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;
contador: inteiro;
resultado: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um número: ")
Leia(numero)

para contador de 1 ate 10 faca
   resultado <- numero * contador
   Escreval(numero, " x ", contador, " = ", resultado)
fimpara

Fimalgoritmo