Algoritmo "soma_100_primeiros"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcular a soma dos cem primeiros números inteiros
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;
soma: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
soma <- 0

para numero de 1 ate 100 faca
   soma <- soma + numero
fimpara

Escreval("A soma dos 100 primeiros números inteiros é: ", soma)

Fimalgoritmo