Algoritmo "impares_0_20"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os números ímpares de 0 a 20
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para numero de 0 ate 20 faca
   se numero mod 2 <> 0 entao
      Escreval(numero)
   fimse
fimpara

Fimalgoritmo