Algoritmo "divisiveis_por_quatro"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os números menores que 200 divisíveis por 4
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
numero: inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para numero de 1 ate 199 faca
   se numero mod 4 = 0 entao
      Escreval(numero)
   fimse
fimpara

Fimalgoritmo