Algoritmo "potencias_de_3"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar as potências de 3 do expoente 0 até 15
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Seção de Declarações das variáveis
expoente: inteiro;
potencia: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
potencia <- 1

para expoente de 0 ate 15 faca
   Escreval("3 elevado a ", expoente, " = ", potencia)
   potencia <- potencia * 3
fimpara

Fimalgoritmo