Algoritmo "celsius_fahrenheit"

// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descricao   : Converter temperaturas de Celsius para Fahrenheit de 10 em 10 graus
// Autor(a)    : Júlia Galvão Almeida Santos
// Data atual  : 18/09/2026

Var
// Secao de Declaracoes das variaveis
celsius: inteiro;
fahrenheit: real;

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...
para celsius de 10 ate 100 passo 10 faca
   fahrenheit <- (9 * celsius + 160) / 5
   Escreval(celsius, " graus Celsius = ", fahrenheit, " graus Fahrenheit")
fimpara

Fimalgoritmo
